### PR TITLE
Create Table section for MQ website

### PR DESCRIPTION
**Pull request by markiiman**
This branch includes:

- Description of the three types of Mustachios
- Table of comparison for each type
- Updates on the Updates section and Progress section
- CSS fixes

### CODE REVIEW

**Comment by markiiman** [comment]
For your review and approval @bernardhistorillo

**Comment by bernardhistorillo** [comment]
15M for 60 days na daw @markii1607

**Comment by bernardhistorillo** [comment]
VERY GOOD MARK! YOU'RE THE BEST!

**Comment by markiiman** [comment]
Thank you!!! HAHAHAHAHA

**Pull request merged**
